# Generated by Django 2.2 on 2019-06-14 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_freekassa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refill',
            options={'verbose_name': 'Refill', 'verbose_name_plural': 'Refills'},
        ),
        migrations.RemoveField(
            model_name='refill',
            name='odobren',
        ),
        migrations.AddField(
            model_name='refill',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='refill',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transact Date'),
        ),
        migrations.AlterField(
            model_name='refill',
            name='sum',
            field=models.FloatField(default=50.0, verbose_name='Amount'),
        ),
        migrations.AlterModelTable(
            name='refill',
            table='refill',
        ),
    ]
