# Generated by Django 2.2 on 2019-06-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_freekassa', '0002_auto_20190614_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.TextField()),
                ('amount', models.TextField()),
                ('card_type', models.CharField(choices=[('visa', 'VISA'), ('btc', 'BTC')], default=('visa', 'VISA'), max_length=128)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at:')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('payed', 'Payed'), ('canceled', 'Canceled'), ('error', 'Error')], default=('opened', 'Opened'), max_length=128, verbose_name='Status')),
                ('comment', models.TextField(help_text='Explanation for the transaction', null=True, verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'db_table': 'withdrawal',
            },
        ),
    ]
