# Generated by Django 2.2 on 2019-06-15 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freekassa', '0003_fundsout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundsout',
            name='id',
        ),
        migrations.AddField(
            model_name='fundsout',
            name='rid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundsout',
            name='amount',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(5000, message='Invalid amount, allowed sum for transaction is 5000$')]),
        ),
        migrations.AlterField(
            model_name='fundsout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at:'),
        ),
    ]
