
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    '5.196.247.5',
    'casino-investment.com',
    'www.casino-investment.com'
]


SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 60
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/account/'

ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_EMAIL_VERIFICATION  = False
EMAIL_HOST = 'mail.casino-investment.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '_mainaccount@casino-investment.com'  # TODO connect mail client
EMAIL_HOST_PASSWORD = '******'
EMAIL_USE_TLS = True
SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


FREEKASSA_ID = "146760"
FREEKASSA_SECRET_1 = "eqbjronj"
FREEKASSA_SECRET_2 = "y0zv4edo"
FREEKASSA_CONVERT = True