# Generated by Django 2.2 on 2019-06-15 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255, verbose_name='Plan Name')),
                ('min_lim', models.IntegerField(verbose_name='Minimal Investition')),
                ('max_lim', models.IntegerField(verbose_name='Maximal Investition Limit')),
                ('period', models.DurationField(help_text='Investition period in days', verbose_name='Period')),
                ('rate', models.FloatField(verbose_name='Daily Rate')),
                ('active', models.BooleanField(default=False, help_text='Plan visibility for new investitions', verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Investition Plan',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='User balance')),
                ('wallet', models.CharField(blank=True, max_length=255, verbose_name='Crypto Wallet')),
                ('email_is_verified', models.BooleanField(default=False, verbose_name='Email верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='InvestActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghid', models.CharField(default='x', max_length=10, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('invested', models.FloatField(verbose_name='Invested')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_active', to='Investions.InvestPlan', verbose_name='Investition Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Investition Active',
            },
        ),
        migrations.AddIndex(
            model_name='investactive',
            index=models.Index(fields=['ghid'], name='Investions__ghid_9efc8a_idx'),
        ),
    ]
