# Generated by Django 2.2 on 2019-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investplan',
            name='period',
            field=models.PositiveSmallIntegerField(help_text='Investition period in days', verbose_name='Period'),
        ),
    ]
