# Generated by Django 2.2 on 2019-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investions', '0003_profile_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('fas fa-phone', 'Phone'), ('fas fa-map-marked-alt', 'Address'), ('fab fa-telegram', 'Telegram'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-viber', 'Viber'), ('fab fa-facebook-f', 'Facebook'), ('fas fa-at', 'E-mail'), ('fab fa-vk', 'Vk.com')], default=('fas fa-phone', 'Phone'), max_length=32, verbose_name='Contact type')),
                ('data', models.CharField(max_length=255, null=True, verbose_name='Contact Data')),
            ],
        ),
    ]
